var names = "Om Kakde";
console.log("Name:", names);
var age = 25;
var temperature = 36.6;
console.log("Age:", age);
console.log("Temperature:", temperature);
var isActive = true;
var isVerified = false;
console.log("Is Active:", isActive);
console.log("Is Verified:", isVerified);
var emptyValue = null;
console.log("Empty Value:", emptyValue);
var notDefined = undefined;
console.log("Not Defined:", notDefined);
var uniqueSymbol = Symbol("unique");
console.log("Symbol:", uniqueSymbol);
